### ISSUE TITLE
Problem with the text editor when something has been pasted

### ISSUE THREAD

**Issue by heitara** [tryboxx/SnippetsLibrary#30]
**Describe the bug**
When creating a snippet with Copy&Paste the editor misbehaves when the user starts typing.

**To Reproduce**
1. Open Xcode and copy a snippet.
2. Click on File -> Add New Snippet
3. Paste the snippet (or any text)
4. Start typing (at least several characters).
5. See the problem

**Expected behavior**
The editor should function as expected.

**Environment:**
 - device: [e.g. MacBook Pro (16-inch, 2019)]
 - macOS: [e.g. Big Sur, version 11.6.2]
 - appVersion: [e.g. 1.0.4 (20)]

**Comment by tryboxx** [comment]
Hello @heitara - thanks for the report. Unfortunately, I cannot recreate this behavior. Can you provide a sample demo that shows this problem?

**Comment by heitara** [comment]
Here is a [video](https://traveljs.apposestudio.com/bug.mov) that illustrates it. (The video will be removed soon.)

**Comment by heitara** [comment]
@tryboxx any update on the above?

**Comment by tryboxx** [comment]
Sure, it should be done by the end of this week - thanks for the attached video 🙂

**Comment by heitara** [comment]
Is it fix, so I can double check it and close the issue?
